command = "cdl/target/${TARGET:-debug}/object-builder"
start-delay = "10s"
start-after = ["schema-registry.toml"]
stdout = "logs/object-builder.log"
stderr = "logs/object-builder.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255 ]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
CDL_CONFIG                      = "cdl/.cdl/development-kafka"

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
